version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - db-storage:/data/db


  backend:
    build: ./server
    volumes:
      - upload-storage:/app/upload
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true

volumes:
  db-storage:
  upload-storage: