apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: service-label
spec:
  selector:
    app: node-app
    tier: backend
  ports:
    - protocol: "TCP"
      port: 90
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    group: deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
      tier: backend
    # matchExpressions:
    # - { key: app, operator: In, values: [node-app] }
    # - { key: app, operator: NotIn, values: [node-app, first-app] }
  template:
    metadata:
      labels:
        app: node-app
        tier: backend
    spec:
      containers:
        - name: node-application
          image: dheeraj1429/node-app
